#ifndef MACROS_h
#define MACROS_h

#define RPL_USERHOST "302" // SO RECEBO E NAO ENVIO (POR ENQUANTO)
#define ERR_NONICKNAMEGIVEN "431"
#define ERR_NICKNAMEINUSE "433"
#define ERR_ALREADYREGISTRED "462"
#define ERR_PASSWDMISMATCH "464"

#endif