#ifndef MACROS_h
#define MACROS_h

#define RPL_USERHOST "302" // SO RECEBO E NAO ENVIO (POR ENQUANTO)
#define ERR_NOORIGIN "409"
#define ERR_UNKNOWNCOMMAND "421"
#define ERR_NONICKNAMEGIVEN "431"
#define ERR_ERRONEUSNICKNAME "432"
#define ERR_NICKNAMEINUSE "433"
#define ERR_NOTREGISTERED "451"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_ALREADYREGISTRED "462"
#define ERR_PASSWDMISMATCH "464"

#endif